title: Your Site Title
description: Your site description
url: "https://zunzun08.github.io"
baseurl: "" # Leave empty for user.github.io sites

plugins:
  - jekyll-feed

# Minima settings (if using minima theme)
minima:
  skin: auto
  social_links:
    github: zunzun08