# Site settings
title: Cristian Compean
description: Portfolio website for Cristian Compean

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# MathJax support
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-toc

remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme