# Site settings
title: Cristian Compean
description: Portfolio website for Cristian Compean
url: "zunzun08.github.io"



theme: minima
# In _config.yml
minima:
  nav_pages:
    - about.html
  skin: auto  # or 'dark', 'solarized', etc.
markdown: kramdown