# Site settings
title: Cristian Compean
description: Portfolio website for Cristian Compean
url: "zunzun08.github.io"



remote_theme: just-the-docs

# Optional: Customize navigation
# See https://just-the-docs.com/docs/navigation-structure/
just_the_docs:
  logo: "/assets/images/logo.png"
  search_enabled: true