theme: minima
plugins:
  - jekyll-feed
baseurl: "/zunzun08.github.io"

# Minima settings
minima:
  skin: auto # light/dark/auto
  social_links:
    github: zunzun08
  footer_content: false  # Disables Minima's default footer
