theme: minima  # Default theme - you can change this

# Site settings
title: Cristian Compean
description: Portfolio website for Cristian Compean

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# MathJax support
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-toc